apiVersion: v1
kind: Pod  
metadata:
  name: pod3
  labels:
    env: development
spec:
    containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo node-select for launch; sleep 5 ; done"]
    nodeSelector:                                         
       hardware: t2-medium
