apiVersion: apps/v1
kind: ReplicaSet  
metadata:
  name: myrs
spec:
  replicas: 2  
  selector:                  
    matchExpressions:               
     - {key: myname, operator: In, values: [Bhupinder, prod]}
     - {key: env, operator: NotIn, values: [production]}
  template:      
    metadata:
      name: pod6
      labels:        
       myname: prod    
       env: dev
    spec:
     containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Replica-set; sleep 5 ; done"]
