apiVersion: v1
kind: ReplicationController  
metadata:
  name: myreplica
spec:
  replicas: 2            
  selector:        
    myname: RC                        
  template:                
    metadata:
      name: pod5
      labels:            
        myname: RC
    spec:
      containers:
        - name: c1
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo RC test; sleep 5 ; done"]
