kind: Service                       
apiVersion: v1
metadata:
  name: service
spec:
  ports:
  - port: 80                               
    targetPort: 80                     
  selector:
    name: deployment
    type: ClusterIP   
